/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantSettingsRouteImport } from './routes/merchant.settings'
import { Route as MerchantProfileRouteImport } from './routes/merchant.profile'
import { Route as MerchantLoanReviewRouteImport } from './routes/merchant.loan-review'
import { Route as MerchantLoanApplicationRouteImport } from './routes/merchant.loan-application'
import { Route as MerchantDocumentsRouteImport } from './routes/merchant.documents'
import { Route as MerchantDashboardRouteImport } from './routes/merchant.dashboard'
import { Route as MerchantCreditScoreRouteImport } from './routes/merchant.credit-score'
import { Route as MerchantAiCoachRouteImport } from './routes/merchant.ai-coach'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminRiskAnalysisRouteImport } from './routes/admin.risk-analysis'
import { Route as AdminPortfolioRouteImport } from './routes/admin.portfolio'
import { Route as AdminMerchantsRouteImport } from './routes/admin.merchants'
import { Route as AdminLoanReviewsRouteImport } from './routes/admin.loan-reviews'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminMerchantDetailsIdRouteImport } from './routes/admin.merchant-details.$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantSettingsRoute = MerchantSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantProfileRoute = MerchantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoanReviewRoute = MerchantLoanReviewRouteImport.update({
  id: '/loan-review',
  path: '/loan-review',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantLoanApplicationRoute = MerchantLoanApplicationRouteImport.update({
  id: '/loan-application',
  path: '/loan-application',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantDocumentsRoute = MerchantDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantDashboardRoute = MerchantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantCreditScoreRoute = MerchantCreditScoreRouteImport.update({
  id: '/credit-score',
  path: '/credit-score',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantAiCoachRoute = MerchantAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => MerchantRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRiskAnalysisRoute = AdminRiskAnalysisRouteImport.update({
  id: '/risk-analysis',
  path: '/risk-analysis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPortfolioRoute = AdminPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantsRoute = AdminMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoanReviewsRoute = AdminLoanReviewsRouteImport.update({
  id: '/loan-reviews',
  path: '/loan-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMerchantDetailsIdRoute = AdminMerchantDetailsIdRouteImport.update({
  id: '/merchant-details/$id',
  path: '/merchant-details/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loan-reviews': typeof AdminLoanReviewsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/risk-analysis': typeof AdminRiskAnalysisRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/ai-coach': typeof MerchantAiCoachRoute
  '/merchant/credit-score': typeof MerchantCreditScoreRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/documents': typeof MerchantDocumentsRoute
  '/merchant/loan-application': typeof MerchantLoanApplicationRoute
  '/merchant/loan-review': typeof MerchantLoanReviewRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/merchant-details/$id': typeof AdminMerchantDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loan-reviews': typeof AdminLoanReviewsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/risk-analysis': typeof AdminRiskAnalysisRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/ai-coach': typeof MerchantAiCoachRoute
  '/merchant/credit-score': typeof MerchantCreditScoreRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/documents': typeof MerchantDocumentsRoute
  '/merchant/loan-application': typeof MerchantLoanApplicationRoute
  '/merchant/loan-review': typeof MerchantLoanReviewRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/merchant-details/$id': typeof AdminMerchantDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/loan-reviews': typeof AdminLoanReviewsRoute
  '/admin/merchants': typeof AdminMerchantsRoute
  '/admin/portfolio': typeof AdminPortfolioRoute
  '/admin/risk-analysis': typeof AdminRiskAnalysisRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/merchant/ai-coach': typeof MerchantAiCoachRoute
  '/merchant/credit-score': typeof MerchantCreditScoreRoute
  '/merchant/dashboard': typeof MerchantDashboardRoute
  '/merchant/documents': typeof MerchantDocumentsRoute
  '/merchant/loan-application': typeof MerchantLoanApplicationRoute
  '/merchant/loan-review': typeof MerchantLoanReviewRoute
  '/merchant/profile': typeof MerchantProfileRoute
  '/merchant/settings': typeof MerchantSettingsRoute
  '/admin/merchant-details/$id': typeof AdminMerchantDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/features'
    | '/login'
    | '/merchant'
    | '/register'
    | '/admin/dashboard'
    | '/admin/loan-reviews'
    | '/admin/merchants'
    | '/admin/portfolio'
    | '/admin/risk-analysis'
    | '/admin/settings'
    | '/merchant/ai-coach'
    | '/merchant/credit-score'
    | '/merchant/dashboard'
    | '/merchant/documents'
    | '/merchant/loan-application'
    | '/merchant/loan-review'
    | '/merchant/profile'
    | '/merchant/settings'
    | '/admin/merchant-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/features'
    | '/login'
    | '/merchant'
    | '/register'
    | '/admin/dashboard'
    | '/admin/loan-reviews'
    | '/admin/merchants'
    | '/admin/portfolio'
    | '/admin/risk-analysis'
    | '/admin/settings'
    | '/merchant/ai-coach'
    | '/merchant/credit-score'
    | '/merchant/dashboard'
    | '/merchant/documents'
    | '/merchant/loan-application'
    | '/merchant/loan-review'
    | '/merchant/profile'
    | '/merchant/settings'
    | '/admin/merchant-details/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/features'
    | '/login'
    | '/merchant'
    | '/register'
    | '/admin/dashboard'
    | '/admin/loan-reviews'
    | '/admin/merchants'
    | '/admin/portfolio'
    | '/admin/risk-analysis'
    | '/admin/settings'
    | '/merchant/ai-coach'
    | '/merchant/credit-score'
    | '/merchant/dashboard'
    | '/merchant/documents'
    | '/merchant/loan-application'
    | '/merchant/loan-review'
    | '/merchant/profile'
    | '/merchant/settings'
    | '/admin/merchant-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/settings': {
      id: '/merchant/settings'
      path: '/settings'
      fullPath: '/merchant/settings'
      preLoaderRoute: typeof MerchantSettingsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/profile': {
      id: '/merchant/profile'
      path: '/profile'
      fullPath: '/merchant/profile'
      preLoaderRoute: typeof MerchantProfileRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/loan-review': {
      id: '/merchant/loan-review'
      path: '/loan-review'
      fullPath: '/merchant/loan-review'
      preLoaderRoute: typeof MerchantLoanReviewRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/loan-application': {
      id: '/merchant/loan-application'
      path: '/loan-application'
      fullPath: '/merchant/loan-application'
      preLoaderRoute: typeof MerchantLoanApplicationRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/documents': {
      id: '/merchant/documents'
      path: '/documents'
      fullPath: '/merchant/documents'
      preLoaderRoute: typeof MerchantDocumentsRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/dashboard': {
      id: '/merchant/dashboard'
      path: '/dashboard'
      fullPath: '/merchant/dashboard'
      preLoaderRoute: typeof MerchantDashboardRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/credit-score': {
      id: '/merchant/credit-score'
      path: '/credit-score'
      fullPath: '/merchant/credit-score'
      preLoaderRoute: typeof MerchantCreditScoreRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/ai-coach': {
      id: '/merchant/ai-coach'
      path: '/ai-coach'
      fullPath: '/merchant/ai-coach'
      preLoaderRoute: typeof MerchantAiCoachRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/risk-analysis': {
      id: '/admin/risk-analysis'
      path: '/risk-analysis'
      fullPath: '/admin/risk-analysis'
      preLoaderRoute: typeof AdminRiskAnalysisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/portfolio': {
      id: '/admin/portfolio'
      path: '/portfolio'
      fullPath: '/admin/portfolio'
      preLoaderRoute: typeof AdminPortfolioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchants': {
      id: '/admin/merchants'
      path: '/merchants'
      fullPath: '/admin/merchants'
      preLoaderRoute: typeof AdminMerchantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loan-reviews': {
      id: '/admin/loan-reviews'
      path: '/loan-reviews'
      fullPath: '/admin/loan-reviews'
      preLoaderRoute: typeof AdminLoanReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/merchant-details/$id': {
      id: '/admin/merchant-details/$id'
      path: '/merchant-details/$id'
      fullPath: '/admin/merchant-details/$id'
      preLoaderRoute: typeof AdminMerchantDetailsIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoanReviewsRoute: typeof AdminLoanReviewsRoute
  AdminMerchantsRoute: typeof AdminMerchantsRoute
  AdminPortfolioRoute: typeof AdminPortfolioRoute
  AdminRiskAnalysisRoute: typeof AdminRiskAnalysisRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminMerchantDetailsIdRoute: typeof AdminMerchantDetailsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoanReviewsRoute: AdminLoanReviewsRoute,
  AdminMerchantsRoute: AdminMerchantsRoute,
  AdminPortfolioRoute: AdminPortfolioRoute,
  AdminRiskAnalysisRoute: AdminRiskAnalysisRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminMerchantDetailsIdRoute: AdminMerchantDetailsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MerchantRouteChildren {
  MerchantAiCoachRoute: typeof MerchantAiCoachRoute
  MerchantCreditScoreRoute: typeof MerchantCreditScoreRoute
  MerchantDashboardRoute: typeof MerchantDashboardRoute
  MerchantDocumentsRoute: typeof MerchantDocumentsRoute
  MerchantLoanApplicationRoute: typeof MerchantLoanApplicationRoute
  MerchantLoanReviewRoute: typeof MerchantLoanReviewRoute
  MerchantProfileRoute: typeof MerchantProfileRoute
  MerchantSettingsRoute: typeof MerchantSettingsRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantAiCoachRoute: MerchantAiCoachRoute,
  MerchantCreditScoreRoute: MerchantCreditScoreRoute,
  MerchantDashboardRoute: MerchantDashboardRoute,
  MerchantDocumentsRoute: MerchantDocumentsRoute,
  MerchantLoanApplicationRoute: MerchantLoanApplicationRoute,
  MerchantLoanReviewRoute: MerchantLoanReviewRoute,
  MerchantProfileRoute: MerchantProfileRoute,
  MerchantSettingsRoute: MerchantSettingsRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
